<?xml version="1.0" encoding="utf-8"?><Database Name="ManagerSystem" Class="ManagerSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=FXCHVH06-V13;Initial Catalog=ManagerSystem;User ID=trainer" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ManagerSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TeacherId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MaterialId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_CourseArrange" Member="CourseArrange" ThisKey="CourseId" OtherKey="CourseId" Type="CourseArrange" Cardinality="One" />
      <Association Name="Course_StudentScore" Member="StudentScores" ThisKey="CourseId" OtherKey="CourseId" Type="StudentScore" />
      <Association Name="Material_Course" Member="Material" ThisKey="MaterialId" OtherKey="MaterialId" Type="Material" IsForeignKey="true" />
      <Association Name="Teacher_Course" Member="Teacher" ThisKey="TeacherId" OtherKey="TeacherId" Type="Teacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CourseArrange" Member="CourseArranges">
    <Type Name="CourseArrange">
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayAndTime" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Course_CourseArrange" Member="Course" ThisKey="CourseId" OtherKey="CourseId" Type="Course" IsForeignKey="true" />
      <Association Name="Room_CourseArrange" Member="Room" ThisKey="RoomId" OtherKey="RoomId" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Department_Major" Member="Majors" ThisKey="DepartmentId" OtherKey="DepartmentId" Type="Major" />
      <Association Name="Department_Teacher" Member="Teachers" ThisKey="DepartmentId" OtherKey="DepartmentId" Type="Teacher" />
    </Type>
  </Table>
  <Table Name="dbo.Major" Member="Majors">
    <Type Name="Major">
      <Column Name="MajorId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MajorName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Department_Major" Member="Department" ThisKey="DepartmentId" OtherKey="DepartmentId" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Manager" Member="Managers">
    <Type Name="Manager">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Material" Member="Materials">
    <Type Name="Material">
      <Column Name="MaterialId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Material_Course" Member="Courses" ThisKey="MaterialId" OtherKey="MaterialId" Type="Course" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="seatNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_CourseArrange" Member="CourseArranges" ThisKey="RoomId" OtherKey="RoomId" Type="CourseArrange" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MajorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Student_StudentScore" Member="StudentScore" ThisKey="StudentId" OtherKey="StudentId" Type="StudentScore" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.StudentScore" Member="StudentScores">
    <Type Name="StudentScore">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_StudentScore" Member="Course" ThisKey="CourseId" OtherKey="CourseId" Type="Course" IsForeignKey="true" />
      <Association Name="Student_StudentScore" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="TeacherId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Teacher_Course" Member="Courses" ThisKey="TeacherId" OtherKey="TeacherId" Type="Course" />
      <Association Name="Department_Teacher" Member="Department" ThisKey="DepartmentId" OtherKey="DepartmentId" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>